[2024-09-25T14:55:31.402+0000] {processor.py:186} INFO - Started process (PID=38) to work on /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:55:31.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_generation_dag.py for tasks to queue
[2024-09-25T14:55:31.404+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:55:31.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:55:31.407+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:55:31.406+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_generation_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_generation_dag.py", line 4, in <module>
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-09-25T14:55:31.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:55:31.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_generation_dag.py took 0.022 seconds
[2024-09-25T14:56:02.111+0000] {processor.py:186} INFO - Started process (PID=101) to work on /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:56:02.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_generation_dag.py for tasks to queue
[2024-09-25T14:56:02.114+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:56:02.114+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:56:02.117+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:56:02.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_generation_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_generation_dag.py", line 4, in <module>
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-09-25T14:56:02.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:56:02.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_generation_dag.py took 0.025 seconds
[2024-09-25T14:56:32.988+0000] {processor.py:186} INFO - Started process (PID=164) to work on /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:56:32.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_generation_dag.py for tasks to queue
[2024-09-25T14:56:32.991+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:56:32.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:56:32.994+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:56:32.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_generation_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_generation_dag.py", line 4, in <module>
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-09-25T14:56:32.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:56:33.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_generation_dag.py took 0.024 seconds
[2024-09-25T14:57:03.586+0000] {processor.py:186} INFO - Started process (PID=227) to work on /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:57:03.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_generation_dag.py for tasks to queue
[2024-09-25T14:57:03.589+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:57:03.589+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:57:03.592+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:57:03.591+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_generation_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_generation_dag.py", line 4, in <module>
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-09-25T14:57:03.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:57:03.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_generation_dag.py took 0.027 seconds
[2024-09-25T14:57:34.117+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:57:34.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_generation_dag.py for tasks to queue
[2024-09-25T14:57:34.121+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:57:34.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:57:34.123+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:57:34.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_generation_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_generation_dag.py", line 4, in <module>
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-09-25T14:57:34.124+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:57:34.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_generation_dag.py took 0.025 seconds
[2024-09-25T14:58:04.933+0000] {processor.py:186} INFO - Started process (PID=353) to work on /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:58:04.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/data_generation_dag.py for tasks to queue
[2024-09-25T14:58:04.936+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:58:04.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:58:04.939+0000] {logging_mixin.py:190} INFO - [2024-09-25T14:58:04.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/data_generation_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/data_generation_dag.py", line 4, in <module>
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-09-25T14:58:04.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/data_generation_dag.py
[2024-09-25T14:58:04.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/data_generation_dag.py took 0.026 seconds
